### ISSUE TITLE
Phase 2 planning: the Stack Club "Syllabus"

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#124]
In the short term, the Stack Club is picking up new members, who could use some guidance as to what order to work through the existing tutorials as a self-taught course. Longer term (think, summer 2019), we can imagine _teaching_ a course on the LSST science pipelines, using the Stack Club tutorials as resources. Both these applications need a course syllabus, so let's start one, and use it to guide our short-term Stack Club activity and longer term planning.

* [x] Make a `SYLLABUS.rst` file in the top level folder that contains a 10-step program for someone looking to work through the Stack Club tutorials in a sensible order., with brief descriptions of each step (session). Include the name of the session (eg "Basics", "Image Processing" etc) 
* [x] Include links to Stack Club resources in the appropriate order
* [ ] Include links to suggested projects, by labeling the project issues by session name and using that label in the link URL.
* [ ] Make any new issues to suggest projects that fill out the syllabus as needed. 

We'll edit this top comment to refine this plan, comments and questions welcome in this thread!

**Comment by kadrlica** [comment]
@drphilmarshall I think I've setup the syllabus structure. I don't know exactly what you have in mind for issuing suggested projects. Would you be willing to take a crack at that?

**Comment by drphilmarshall** [comment]
I'll have a go at defining some placeholder issues based on the gaps that are showing up in the [Syllabus.md file](https://github.com/LSSTScienceCollaborations/StackClub/blob/syllabus/Syllabus.md) you made - and I'll attempt the topic labeling while I'm at it.

**Comment by kadrlica** [comment]
Discussions from our stack club breakout with @bechtol @ih64 @kadrlica and @jimbosch.

1. Basics
   - JB: calexp is probably the wrong name... this object is an afw.image.exposure
   - JB: change name to something about "getting and working with images"
2. Getting Started
   - ADW: This may not be covered in a course that is not aimed at recruiting Stack Club members
   - KB: This would be an excellent resource if references are up to date   
   - KB: Might be useful to create: 1 hour, 8 hour, 40 hour courses
3. Visualization 
   - JB: Is Firefly used?
   - ADW: Not so much. Due to familiarity with mpl and static rendering, we aren't using Firefly too much.
4. Processing Single Visits
   - ADW: Probably deep dive into setting parameters
6. Image Coaddition
   - JB: Some discussion of different coaddition schemes
   - JB: Need a lot of metadata and structure
   - JB: Might need intro to data repos and 
7. Sky background estimation
   - IH: Heard from robert that there has been work on sky background estimation
   - IH: Do we have an idea of how to validate sky background? Good topic to add.
   - JB: Best sky background will probably require complicated interface to large data sets (multiple CCDs/exposures). Could be hard to deal with in notebook format.
   - IH: Maybe a low hanging fruit could be an intro notebook
   ** JB: How do you estimate the background in a naive way with one image.
   ** JB: How do you get the background from a full cli processing task

General Discussion:
* JB: Might make sense to reorder to: Background, Detection, Deblending, Measurement, PSF
* JB: Could split up the ISR part of Single Visit and the other components of bkg, sources, etc.
* KB: Notes that there is a workshop focused on ISR
* JB: A lot of people come with pre-ISR corrected data
* ADW: ISR is probably worth bringing back into the syllabus
* JB: Has some notebooks for overview of image characterization: 
* IH: Like to mirror process CCD in the image characterization tasks
* JB: In order to fill some of these later topics, might need to dive deep into visualizing issues.
* JB: Photometric and Astrometric calibration could be combined
* KB: One thing that is missing is the broad overview of the concepts of the stack.
* JB: DM had a bootcamp that generated a lot of material that is mostly up to date.

**Comment by kadrlica** [comment]
@drphilmarshall how are we doing with the remaining bullets on this issue?

**Comment by kadrlica** [comment]
This is closed. The Stack Club Course ran successfully [here](https://github.com/LSSTScienceCollaborations/StackClubCourse)
