### ISSUE TITLE
Project: Explain source detections, footprints

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#131]
Here's an idea for a short Stack Club tutorial: a notebook that explains and illustrates the difference between CoaddSources and Sources, Footprints and Heavy Footprints,  in a small patch of the HSC survey. 
- How are (visit image) Sources' positions and fluxes related to the (coadd image) CoaddSources' positions and fluxes? Are they linked by a common ID? Does the average Source resemble the CoaddSource?
- What is a footprint, and what is a heavy footprint?

Labelling this as "discussion" as I think this project concept needs some more thought.

**Comment by ih64** [comment]
Hi @drphilmarshall , I'd be happy to work on this a bit, since I feel like I punted on the topic of footprints a bit in my afw_table notebook. I have an experimental notebook I started working on during our hack last Friday (going to do a first push soon). So far it just has some info on footprints and heavy footprints, but has not considered single visit vs coadd. 

@kadrlica pointed out in [the stack club seedling google doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#heading=h.r6apltqpk2mf) that deblending is tied up in this too. Maybe we can flesh that conversation out in this thread too.

Something I've been wondering is how 'Peaks' are related to measurement, deblending, and footprints. Admittedly dont really know anything  about them, but they might fit into this discussion too since one can access them through footprints.

**Comment by drphilmarshall** [comment]
Sounds good - thanks Imran! Keep us posted.

**Comment by ih64** [comment]
Hi Phil,

I'm looking at the issue again after doing some work on the footprints notebook. At the moment it discusses footprints and heavyfootprints, but does not explore the single visit - coadd connection 😞 

i got carried away learning about the basics of footprints and I wound up fleshing out footprints on their own quiet a bit. I also went into their connection to detection, deblending, and measurement, which are items in the source detection lesson on the stack club google doc .Alex's LowSurfaceBrightness notebook touches on these too, and I tried my best to make this new notebook complimentary rather than repetitive. I hope it is still useful to folks learning about the stack. If not I can scrap it and retool it to focus on other stack club goals
