### ISSUE TITLE
DM Stack Club meeting tomorrow, March 8, 9AM PST

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/StackClub#187]
Stack Club friends, 

After a bit of hiatus, we will reconvene in our usual Stack Club venue tomorrow, Fri. March 8th, at 9AM PST.  The plan is to cover matters relevant to the Club which were discussed at the DESC meeting in Berkeley last week, and (hopefully) hear about the Release 17 of the LSST Science Pipeline.  Somehow, I think that the DM guys would love to hear of any problems we might encounter!  To this end, we might consider re-running our existing notebooks using the Release 17.  After this, we will continue hacking / testing, and we will finish at 11AM.  But, if anyone has a notebook which they would like to share - we'd love to hear about it!  

See you tomorrow, on http://stanford.zoom.us/j/946390572

Phil, Greg & Alex

**Comment by drphilmarshall** [comment]
Notes from the Release 17.0 discussion:
* Parallel ingest should speed things up! @andrewkbradshaw and @kadrlica interested in exploring
* ISR is now more consolidated, and refactored to look more like the other tasks (so should be more unified/robust). @andrewkbradshaw is testing his notebooks using v17.  Obs package functionality might have changed for you - watch out...
* Alert production! A slew of new notebook opportunities. Includes DIA but also object association and prompt product database (PPDB) filling. @ebellm will point us at the HITS data in the LSP that has been used for testing (and would be good to develop Stack Club tutorials against)
    * Recommendations for examples/demos to build tutorials from? Prompt product database is the most interesting new thing - contains DIASources and DIAObjects (with incomplete measurements). Plenty of scope for science-oriented notebooks that probe this dataset. NB. THere is no alert database yet. 
* `obs_lsst` is now in `lsst_distrib` so is available without extra set-up. (If you have put it on yoru path already, it'll need removing otherwise it could interfere with your v17 setup.) `obs_lsst` supports work on images from LSSTCam (later), the beam sim at Davis (possibly), AuxTel, the camera test stands at SLAC, PhoSim and ImSim. Code is pretty new and could be rough around the edges... 
* DCR -correction in templates - best ignore for now, still under development!
* Astrometric matching improvements: no need to change tutorials but watch for new problems when processing images.
* Gen 3 middleware: the Gen 3 butler can be played with, but probably best leaving this alone for now. The Gen 2 butler is not deprecated yet. Summoning a `butler` from `dafPersist`will still get you a Gen 2 butler.

Other things:
* Watch out for variable name changes in the release notes.
* New format reference catalogs for a particular data repo? Where do these live? Any change in how to access these? Astrometry.net are old style, use the htm folder instead.

More questions about v17? -> #dm-science-pipelines or #dm-newbies  For alert production there is also #dm-alert-prod
