### ISSUE TITLE
Add guidance on which release to use

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#74]
On jupyterlab start-up. I guess this goes in all of Hello World, GettingStarted.md, and the README, in that we should say repeatedly, we develop against the most recent release unless there is good reason not to (like, a particular new function is needed). It'd be good to only say in one place what that most recent release is - perhaps on the main README. 

This is separate from noting which release each notebook was last verified on - in principle they should all say the most recent release, but they may not (for one reason or another).

**Comment by PaulPrice** [comment]
There are releases and releases. I think you want to be developing against the most recent *major* release (modulo any bugfixes), which is currently `16.0`. I think it would be best to avoid the daily and weekly releases in general.

**Comment by jtmyles** [comment]
The [LSST Science Platform Notebook Aspect tutorial](https://nb.lsst.io/getting-started/logging-in.html) that new users are likely to use while getting setup on the platform suggests using the latest daily release. I think it would be good for the main `README` to say that its suggested release takes precedence over the notebook tutorial so that new users can follow unambiguous directions.

**Comment by drphilmarshall** [comment]
@jtmyles those LSP docs say that _developers_ of the LSP shoudl use the most recent daily, but users like us should use a supported release or the most recent weekly. Our CIT script uses the supported release via `--kernel lsst`, so for this reason and Paul's above, we should go with that. I'll check our docs now and then close this out.
